services:
  - postgres:latest
  - rabbitmq:latest

variables:
  TEST_FOLDER: database
  DOCKER_IMAGE: ${CI_REGISTRY}/acs/public/villas/web-backend-go
  DOCKER_IMAGE_DEV: ${CI_REGISTRY}/acs/public/villas/web-backend-go/dev
  POSTGRES_DB: testvillasdb
  POSTGRES_USER: villas
  POSTGRES_PASSWORD: villas
  POSTGRES_HOST: postgres
  RABBITMQ_DEFAULT_USER: villas
  RABBITMQ_DEFAULT_PASS: villas
  AMQP_URL: 'amqp://villas:villas@rabbitmq:5672'

stages:
  - prepare
  - build
  - test
  - deploy

# Stage: prepare
##############################################################################

# Build docker images
prepare:redoc:
  stage: prepare
  script:
    - docker build -f doc/api/Dockerfile -t redoc .
  tags:
    - shell
    - linux

# Stage: build
##############################################################################

build:backend:
  stage: build
  tags:
    - docker
  image: golang:1.12.9-buster
  script:
    - go mod tidy
    - go install github.com/swaggo/swag/cmd/swag
    - swag init -p pascalcase -g "start.go" -o "./doc/api/"
    - go build
  artifacts:
    paths:
      - doc/api/swagger.json
      - doc/api/docs.go

build:docker:
  stage: build
  tags:
    - shell
    - linux
  script:
    - docker build -t ${DOCKER_IMAGE} .


# Stage: test
##############################################################################

test:apidoc:
  stage: test
  tags:
    - docker
  image: redoc
  script:
    - cd doc/api
    - redoc-cli bundle --cdn --title "VILLASweb Backend API Documentation" --output index.html swagger.json
  dependencies:
    - build:backend
  artifacts:
    paths:
      - doc/api/index.html
      - doc/api/swagger.json

test:all:
  stage: test
  tags:
    - docker
  image: golang:1.12.9-buster
  script:
    - go mod tidy
    - go test $(go list ./... )
       -p 1
       -covermode=count
       -coverprofile ./testcover.txt
       -dbname ${POSTGRES_DB}
       -dbhost ${POSTGRES_HOST}
       -dbuser ${POSTGRES_USER}
       -dbpass ${POSTGRES_PASSWORD}
       -amqp ${AMQP_URL}
    - go tool cover -func=testcover.txt
  dependencies:
    - build:backend

test:database:
  stage: test
  tags:
    - docker
  image: golang:1.12.9-buster
  script:
    - go mod tidy
    - cd ${TEST_FOLDER}
    - go test -v -args
       -dbname ${POSTGRES_DB}
       -dbhost ${POSTGRES_HOST}
       -dbuser ${POSTGRES_USER}
       -dbpass ${POSTGRES_PASSWORD}
       -amqp ${AMQP_URL}
  dependencies:
    - build:backend

test:scenario:
  extends: test:database
  variables:
    TEST_FOLDER: routes/scenario

test:simulationmodel:
  extends: test:scenario
  variables:
    TEST_FOLDER: routes/simulationmodel

test:signal:
  extends: test:database
  variables:
    TEST_FOLDER: routes/signal

test:dashboard:
  extends: test:database
  variables:
    TEST_FOLDER: routes/dashboard

test:widget:
  extends: test:database
  variables:
    TEST_FOLDER: routes/widget

test:simulator:
  extends: test:database
  variables:
    TEST_FOLDER: routes/simulator

test:file:
  extends: test:database
  variables:
    TEST_FOLDER: routes/file

test:user:
  extends: test:database
  variables:
    TEST_FOLDER: routes/user

test:healthz:
  extends: test:database
  variables:
    TEST_FOLDER: routes/healthz

# Stage: deploy
##############################################################################

deploy:docker:
  stage: deploy
  before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker push ${DOCKER_IMAGE}
  dependencies:
    - build:docker
  only:
    - master
  tags:
    - shell
    - linux

# deploy:upload:
#   stage: deploy
#   script:
#     - cd doc/api
#     - rsync --copy-links --chown ${DEPLOY_USER}:${DEPLOY_USER} index.html swagger.json ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}
#   dependencies:
#     - test:apidoc
#   only:
#     - master
#   tags:
#     - shell
