variables:
  DEPLOY_USER: deploy
  DEPLOY_HOST: acs-os-fein-website
  DEPLOY_PATH: /var/www/villas/api/web/
  TEST_FOLDER: routes/simulation

stages:
  - prepare
  - build
  - test
  - deploy

# Stage: prepare
##############################################################################

# Build docker images
prepare:redoc:
  stage: prepare
  script:
    - docker build -f doc/api/Dockerfile -t redoc .
  tags:
    - shell
    - linux

prepare:ubuntu:
  stage: prepare
  script:
    - docker build -f Dockerfile.ubuntu -t villaswebbackendgo:ubuntu .
  tags:
    - shell
    - linux

# Stage: build
##############################################################################

build:backend:
  stage: build
  tags:
    - docker
  image: villaswebbackendgo:ubuntu
  script:
    - go mod tidy
    - go get -u github.com/swaggo/swag/cmd/swag
    - ~/go/bin/swag init -p pascalcase -g "start.go" -o "./doc/api/"
    - go build
  artifacts:
    paths:
      - doc/api/swagger.json

# Stage: test
##############################################################################

test:api:bundle:
  stage: test
  tags:
    - docker
  image: redoc
  script:
    - cd doc/api
    - redoc-cli bundle --cdn --title "VILLASweb Backend API Documentation" --output index.html swagger.json
  dependencies:
    - build:backend
  artifacts:
    paths:
      - doc/api/index.html
      - doc/api/swagger.json

test:database:
  stage: test
  tags:
    - docker
  image: villaswebbackendgo:ubuntu
  script:
    - /etc/init.d/postgresql start
    - go mod tidy
    - go get -u github.com/swaggo/swag/cmd/swag
    - ~/go/bin/swag init -p pascalcase -g "start.go" -o "./doc/api/"
    - cd common
    - go test -v -args -dbhost=/var/run/postgresql
  dependencies:
    - build:backend

test:simulation:
  stage: test
  tags:
    - docker
  image: villaswebbackendgo:ubuntu
  script:
    - /etc/init.d/postgresql start
    - go mod tidy
    - go get -u github.com/swaggo/swag/cmd/swag
    - ~/go/bin/swag init -p pascalcase -g "start.go" -o "./doc/api/"
    - cd ${TEST_FOLDER}
    - go test -v -args -dbhost=/var/run/postgresql
  dependencies:
    - build:backend

test:simulationmodel:
  extends: test:simulation
  variables:
    TEST_FOLDER: routes/simulationmodel

test:visualization:
  extends: test:simulation
  variables:
    TEST_FOLDER: routes/visualization

test:widget:
  extends: test:simulation
  variables:
    TEST_FOLDER: routes/widget
# Stage: deploy
##############################################################################

deploy:upload:
  stage: deploy
  script:
    - cd doc/api
    - rsync --copy-links --chown ${DEPLOY_USER}:${DEPLOY_USER} index.html swagger.json ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}
  dependencies:
    - test:api:bundle
  only:
    - master
  tags:
    - shell
