variables:
  DEPLOY_USER: deploy
  DEPLOY_HOST: acs-os-fein-website
  DEPLOY_PATH: /var/www/villas/api/web/

stages:
  - prepare
  - build
  - test
  - deploy

# Stage: prepare
##############################################################################

# Build docker images
prepare:redoc:
  stage: prepare
  script:
    - docker build -f doc/api/Dockerfile -t redoc .
  tags:
    - shell
    - linux

prepare:ubuntu:
  stage: prepare
  script:
    - docker build -f Dockerfile.ubuntu -t villaswebbackendgo:ubuntu .
  tags:
    - shell
    - linux

# Stage: build
##############################################################################

build:doc:api:
  stage: build
  tags:
    - docker
  image: redoc
  script:
    - cd doc/api
    - redoc-cli bundle --cdn --title "VILLASweb Backend API Documentation" --output index.html api.yaml
  artifacts:
    paths:
      - doc/api/index.html

build:backend:
  stage: build
  tags:
    - docker
  image: villaswebbackendgo:ubuntu
  script:
    - go mod tidy
    - go get -u github.com/swaggo/swag/cmd/swag
    - swag init -p pascalcase -g "start.go" -o "./doc/autoapi/"
    - go build


# Stage: test
##############################################################################

test:backend:database:
  stage: test
  tags:
    - docker
  image: villaswebbackendgo:ubuntu
  script:
    - /etc/init.d/postgresql start
    - go mod tidy
    - go get -u github.com/swaggo/swag/cmd/swag
    - swag init -p pascalcase -g "start.go" -o "./doc/autoapi/"
    - cd common
    - go test -v -args -dbhost=/var/run/postgresql
  dependencies:
    - build:backend

test:backend:endpoints:
  stage: test
  tags:
    - docker
  image: villaswebbackendgo:ubuntu
  script:
    - /etc/init.d/postgresql start
    - go mod tidy
    - go get -u github.com/swaggo/swag/cmd/swag
    - swag init -p pascalcase -g "start.go" -o "./doc/autoapi/"
    - cd endpoints
    - go test -v -args -dbhost=/var/run/postgresql
  dependencies:
    - build:backend

# Stage: deploy
##############################################################################

deploy:upload:
  stage: deploy
  script:
    - cd doc/api
    - rsync --copy-links --chown ${DEPLOY_USER}:${DEPLOY_USER} index.html api.yaml ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}
  dependencies:
    - build:doc:api
  only:
    - master
  tags:
    - shell
